server:
  port: 18880
  tomcat:
    max-http-form-post-size: 20MB

spring:
  profiles:
    active: @profileActive@

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liko.model
  configuration:
    map-underscore-to-camel-case: true
